Shader "Matej Vanco/RayMarcher/Mobile/RM Master_Example_Mobile_Castle"
{

	//-----------The shader was generated by the RM_XConvertor - Please do not change any property nor location of the shader

	Properties
	{
			[NoScaleOffset]
			_MASrenderMainFilter("Render Filter [INTERNAL USE]",2D) = "white"{}

			//----------RENDER SECTION-------------------------
			//---RENDER : Textures & Colors
			_MASrenderMainColor("Base Color", Color) = (1,1,1,1)
			_MASrenderSecondColor("Secondary Color", Color) = (1,0.5,0,1)
			[NoScaleOffset]
			_MAScolorRamp("Color Ramp",2D) = "white"{}

			//---RENDER : Quality & Render Settings
			_MASrenderMaxDistance("Render Distance", Float) = 10
			[Toggle]_MASrenderQualitySetting("Simple Render", Int) = 0
			_MASrenderQuality("Render Quality", Range(0.5,0.0001)) = 0.005

			//---RENDER : Rendering Options [Soft Outline, Cell Shading, Specular]
			_MASrenderOutlineSoft("Outline Softness", Float) = 1
			_MASrenderOutlineDens("Outline Density", Float) = 1

			_MASrenderToonThresh("Cel Threshold", Float) = 1
			_MASrenderToonDens("Cel Density", Float) = 1

			_MASrenderLightDir("Light Direction", Vector) = (0,-1,0,0)
			_MASrenderShadowUmbraIntens("Shadow Umbra Intensity", Range(0,1)) = 0.1

			_MASrenderSpecularIntens("Specular Intensity",Range(0,2)) = 0.5
			_MASrenderSpecularSize("Specular Size",Range(0,9.99)) = 1

			_MASrenderSmoothness("Global Smoothness", Float) = 0
			_MASrenderColorSmoothness("interFinalColor Smoothness", Float) = 0

			//----------GLOBAL OPERATIONS SECTION-------------------------
			//---GLOBAL OPERATIONS : Fragment[MobileOnly] + Loop
			_OPfragmentSize("Fragment Size", Vector) = (1,1,1,1)
			_OPfragmentDirect("Fragment Direction", Vector) = (1,1,1,1)

			[Toggle]_OPloopEnabled("Loop Operation", Int) = 0
			_OPloopTilling("Loop Tilling", Vector) = (10,10,10,10)
			[Toggle]_OPloopTwoDimens("Loop Two Dimensional", Int) = 0

			//---Internal macros & info for developer----
			//-Master/Major functions & variables starting with MAS
			//-Macro/Define functions & variables starting with MA
			//-Generator functions & variables starting with GEN
			//-Operation functions & variables starting with OP

			//-All internal shader variables starting with inter
	}
	SubShader
	{	
		Cull Off ZWrite Off ZTest Always

		Pass
		{
			CGPROGRAM

				#pragma vertex MAS_Vertex
				#pragma fragment MAS_Fragment
				#pragma target 3.0
				#include "UnityCG.cginc"

				#define RENDER_LAMBERT
				#define RENDER_OUTLINE
				

				#include "Includes\Mobile\Raymarch_Properties.cginc"

				#include "Includes\Mobile\Raymarch_Vert.cginc"

				#include "Includes\Mobile\Raymarch_Operators.cginc"

				#include "ShapeSources\Raymarch_ShapesSource_Example_Mobile_Castle.cginc"

				#include "Includes\Mobile\Raymarch_FractsSource.cginc"

				#include "ObjectBuffers\Raymarch_ObjectBuffer_Example_Mobile_Castle.cginc"	

				#include "Includes\Mobile\Raymarch_Core.cginc"

				#include "Includes\Mobile\Raymarch_Frag.cginc"

			ENDCG
		}
	}
}
